## **Import libraries**

In [ ]:
import pandas as pd
import numpy as np

# **Upload the datasets**

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving ames_data_2.xlsx to ames_data_2.xlsx
Saving AMES_dataset3.csv to AMES_dataset3.csv
Saving OASIS.xlsx to OASIS.xlsx

# **Read the datasets**

In [ ]:
oasis = pd.read_excel("OASIS.xlsx")

data2 = pd.read_excel("ames_data_2.xlsx")

data3 = pd.read_csv("AMES_dataset3.csv")

# Check the datasets

In [ ]:
print("OASIS")
print(oasis.shape)
print(oasis.columns)

print("\nDataset2")
print(data2.shape)
print(data2.columns)

print("\nDataset3")
print(data3.shape)
print(data3.columns)

OASIS
(25360, 22)
Index(['#', 'CAS Number', 'SMILES', 'EndpointPath', 'Database', 'Author',
       'Strain', 'Endpoint', 'Record ID', 'Test type', 'Type of method',
       'Metabolic activation', 'Type of genotoxicity',
       'Test organisms (species)', 'Source of methabolic system',
       'Assigned SMILES', 'Value.MeanValue', 'Value.Scale', 'Year',
       'Original value.MeanValue', 'Original value.Scale', 'Reference source'],
      dtype='object')

Dataset2
(8576, 4)
Index(['smiles', 'ID', 'endpoint', 'MW'], dtype='object')

Dataset3
(7278, 3)
Index(['Drug_ID', 'Drug', 'Y'], dtype='object')

**Extract only the SMILES string and toxicity label from the OASIS dataset.**

In [ ]:
oasis = oasis[['SMILES','Value.MeanValue']]

# **Convert Labels**

In [ ]:
oasis['Label'] = oasis['Value.MeanValue'].map({
    'Positive':1,
    'Negative':0
})

oasis = oasis[['SMILES','Label']]

# **Dataset_2**

In [ ]:
data2 = data2[['smiles','endpoint']]
data2.columns = ['SMILES','Label']

# **Dataset_3**

In [ ]:
data3 = data3[['Drug','Y']]
data3.columns = ['SMILES','Label']

**#  Add Source dataset for each compound**

In [ ]:
oasis['Source'] = 'OASIS'
data2['Source'] = 'Dataset2'
data3['Source'] = 'Dataset3'

# Merge the datasets

In [ ]:
master = pd.concat(
    [oasis,data2,data3],
    ignore_index=True
)

**Check the merged dataset**

In [ ]:
print(master.shape)

master.head()

(41214, 3)

       SMILES  Label Source
0  FOC(F)(F)F    NaN  OASIS
1  O=Cc1ccco1    0.0  OASIS
2  O=Cc1ccco1    1.0  OASIS
3  O=Cc1ccco1    0.0  OASIS
4  O=Cc1ccco1    0.0  OASIS

**Check Missing Values**

In [ ]:
master.isnull().sum()

SMILES       2
Label     5023
Source       0
dtype: int64

**Check missing labels by source**

In [ ]:
master[master['Label'].isna()]['Source'].value_counts()

Series([], Name: count, dtype: int64)

**Check label datatype**

In [ ]:
master['Label'].dtype

dtype('float64')

**Count the missing labels**

In [ ]:
master['Label'].isna().sum()

np.int64(0)

**Remove rows with missing SMILES**

In [ ]:
master = master.dropna(subset=['SMILES'])

**Dataset Size**

In [ ]:
print(master.shape)

(36191, 3)

**Check the dataset size**

In [ ]:
print("OASIS:", oasis.shape)
print("Dataset2:", data2.shape)
print("Dataset3:", data3.shape)

OASIS: (25360, 3)
Dataset2: (8576, 3)
Dataset3: (7278, 3)

**Check how many rows each source contributed**

In [ ]:
master['Source'].value_counts()

Source
OASIS       20337
Dataset2     8576
Dataset3     7278
Name: count, dtype: int64

**Merge Datasets**

In [ ]:
master = pd.concat([oasis, data2, data3], ignore_index=True)

print(master.shape)

(41214, 3)

**Check missing values**

In [ ]:
master.isnull().sum()

SMILES       2
Label     5023
Source       0
dtype: int64

**Print the column names**

In [ ]:
print(oasis.columns)

Index(['SMILES', 'Label', 'Source'], dtype='object')

**Read the original OASIS dataset from the Excel file.**

In [ ]:
oasis_raw = pd.read_excel("OASIS.xlsx")

**Display the column names in the original OASIS dataset.**

In [ ]:
print(oasis_raw.columns)

Index(['#', 'CAS Number', 'SMILES', 'EndpointPath', 'Database', 'Author',
       'Strain', 'Endpoint', 'Record ID', 'Test type', 'Type of method',
       'Metabolic activation', 'Type of genotoxicity',
       'Test organisms (species)', 'Source of methabolic system',
       'Assigned SMILES', 'Value.MeanValue', 'Value.Scale', 'Year',
       'Original value.MeanValue', 'Original value.Scale', 'Reference source'],
      dtype='object')

**Examine original OASIS labels**

In [ ]:
oasis_raw['Value.MeanValue'].value_counts(dropna=False)

Value.MeanValue
Negative    17309
NaN          5023
Positive     3028
Name: count, dtype: int64

In [ ]:
# Keep only labeled compounds
oasis = oasis_raw[['SMILES', 'Value.MeanValue']].copy()

# Remove rows without an assigned label
oasis = oasis.dropna(subset=['Value.MeanValue'])

# Map labels
oasis['Label'] = oasis['Value.MeanValue'].map({
    'Positive': 1,
    'Negative': 0
})

# Keep final columns
oasis = oasis[['SMILES', 'Label']]
oasis['Source'] = 'OASIS'

**Build master dataset**

In [ ]:
master = pd.concat([oasis, data2, data3], ignore_index=True)

print(master.shape)

(36191, 3)

**Save the master dataset**

In [ ]:
master.to_csv("master_raw.csv", index=False)

print("Master dataset saved successfully!")

Master dataset saved successfully!

** Export the final master dataset to a CSV file.**

In [ ]:
master.to_csv("master_raw.csv", index=False)

**Download the dataset**

In [ ]:
from google.colab import files

files.download("master_raw.csv")